### ISSUE TITLE
Support CSS modules

### ISSUE THREAD

**Issue by alexlafroscia** [alexlafroscia/postcss-syntax.vim#1]
https://github.com/css-modules/css-modules
- [ ] Add support for the `composes` syntax
  
  ``` css
  .foo {
    composes: baz from './base';
  }
  .bar {
     composes: foo;
  }
  ```
- [ ] Support `:local` and `:global` for scoping rules
## Before

`:local` and `:global`

<img width="316" alt="screen shot 2016-07-16 at 2 28 50 pm" src="https://cloud.githubusercontent.com/assets/1645881/16897294/b1a7d6cc-4b61-11e6-8ac9-146dfa7e4a1d.png">
